backend:
  name: git-gateway
  branch: master
  accept_roles:
    - admin

site: https://revolver-inc.netlify.com/

media_folder: static/assets
public_folder: /assets

collections:
  # Static Pages
  - name: "pages"
    label: "Pages"
    delete: false
    identifier_field: name
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index-page"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "index-page",
            }
          - { label: Title, name: title, widget: "hidden", default: "Revolver" }
          - label: "Introduction / Hero Text"
            name: "intro"
            widget: "object"
            fields:
              - { label: Heading, name: heading, widget: string }
              - { label: Introduction Text, name: introBody, widget: markdown }
              - { label: Featured Image, name: featuredImage, widget: image }
          - label: "The Latest (News)"
            name: "news"
            widget: "object"
            fields:
              - {
                  label: "Display News?",
                  name: newsIsVisible,
                  widget: boolean,
                  default: true,
                  hint: "This toggle needs to be to the left if you want it to display.",
                }
              - { label: "News Title", name: newsHeading, widget: string }
              - { label: "News Body", name: body, widget: markdown }
              - { label: "News Image", name: newsImage, widget: image }

      - file: "src/pages/discover.md"
        label: "Discover Page"
        name: "discover-page"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "discover-page",
            }
          - { label: Title, name: title, widget: "hidden", default: "Discover" }
          - {
              label: "Heading Text",
              name: discoverHeading,
              widget: string,
              default: "There's always something new at Revolver.",
            }

      - file: "src/pages/trade.md"
        label: "Trade Page"
        name: "trade-page"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "trade-page",
            }
          - { label: Title, name: title, widget: "hidden", default: "Trade" }
          - {
              label: "Heading Blurb",
              name: "headingBlurb",
              widget: "text",
              default: "We will buy your old records, movies and Dvd's!",
              hint: "This goes at the top of the web page. Try to keep it brief.",
            }
          - label: "Trade F.A.Q."
            name: "tradeFAQ"
            widget: "list"
            fields:
              - {
                  label: "Question",
                  name: question,
                  widget: string,
                  default: "How do trades work?",
                  hint: "Enter a question a customer might have about trades",
                }
              - { label: "Answer", name: answer, widget: markdown }
          - { label: "Trade Legalese", name: body, widget: markdown }

      - file: "src/pages/contact.md"
        label: "Contact Page"
        name: "contact-page"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "contact-page",
            }
          - { label: Title, name: title, widget: "hidden", default: "Contact" }
          - { label: "Body Text", name: body, widget: markdown }

  # # dynamic pages
  - name: "locations"
    identifier_field: name
    label: "Locations"
    folder: src/data/locations
    create: true
    extension: json
    format: json
    slug: "{{slug}}"
    fields:
      - { label: "Location Name", name: "name", widget: "string" }
      - { label: "Store Location", name: location, widget: "map" }
      - {
          label: "Store Map (Interior)",
          name: "mallImg",
          widget: "image",
          required: false,
          hint:"Use a picture of the mall interior map.",
        }
      - { label: "Address", name: "address", widget: "string" }
      - { label: "City", name: "city", widget: "string" }
      - {
          label: "Province",
          name: "province",
          widget: "string",
          hint: "Abbreviate to two characters (Ex: Alberta = AB)",
        }
      - { label: "Postal Code", name: "postalCode", widget: "string" }
      - { label: "Phone Number", name: "phoneNumber", widget: "string" }
      - { label: "Hours", name: "hours", widget: "text" }

  - name: "products"
    label: "Products"
    identifier_field: name
    folder: "src/pages/products/"
    create: true
    slug: "{{name}}"
    # slug: "{{year}}-{{month}}-{{day}}-{{hour}}-{{minute}}-{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "product-page",
        }
      - label: "Product Category"
        name: "productType"
        widget: "select"
        options:
          - { label: "Music", value: "MUSIC" }
          - { label: "DVD/Blu-Ray", value: "MOVIE" }
          - { label: "Merchandise", value: "MERCH" }
      - {
          label: "Unique Product Name",
          name: name,
          widget: string,
          hint: "Does not accept spaces. This field is important, the website uses it internally. You will use it to control the position of featured products, so make it human-readable. Example: MUSIC-Nirvana-Nevermind",
          pattern: ["^\\S*$", "No spaces allowed in product name!"],
        }
      - {
          label: "Artist / Product Name",
          name: "title",
          widget: "string",
          hint: "This is the heading that will show up on the website",
        }
      - {
          label: "Album Title/ Product Subtitle",
          name: "subtitle",
          widget: "string",
          hint: "This is required to properly sort products. If product has no sub-title, describe the type of item it is.",
        }
      - {
          label: "Genre/Category",
          name: genre,
          widget: string,
          required: false,
          hint: "Not required",
        }
      - label: "Product Image"
        name: "productImg"
        widget: "image"
        media_library:
          config:
            multiple: false
      - {
          label: "Year Released",
          name: "year",
          widget: "number",
          required: false,
          hint: "Optional value.",
        }
      - {
          label: "Local",
          name: isLocal,
          widget: boolean,
          default: false,
          hint: "Was this product made in Canada?",
        }
      - {
          label: "Condition",
          name: "condition",
          widget: string,
          default: "Vinyl (Mint)",
          required: false,
          hint: "Describe the object. CD / DVD? Album? What condition is it in? Not required.",
        }
      - {
          label: "Listen Link / Trailer Link",
          name: mediaUrl,
          widget: string,
          required: false,
        }
      - { label: "Body", name: "body", widget: "markdown" }
      - {
          label: "Tags",
          name: "tags",
          widget: "list",
          required: false,
          hint: "Write tags to describe the object. Separate tags with a comma.",
        }
      - {
          label: "Nerd Numbers",
          name: id,
          widget: "uuid",
          description: "Unique Identifier used to id products. DO NOT CHANGE.",
          hint: "You shouldn't be able to change this. If you can, something has gone wrong, don't change it.",
          required: false,
        }

  - name: "productLists"
    identifier_field: name
    label: "Product Listings"
    delete: false
    files:
      - label: "Featured Products"
        name: "featuredProducts"
        file: "src/data/featured.json"
        fields:
          - {
              label: Title,
              name: title,
              widget: hidden,
              default: "featured-products",
            }
          - label: "Featured Listing"
            name: "featuredList"
            description: "Arrange this list to control position of featured items."
            widget: "list"
            fields:
              - label: "Product"
                name: "product"
                widget: "relation"
                collection: "products"
                searchFields: ["productType", "title", "subtitle"]
                valueField: "name"
                displayFields: ["productType", "title", "subtitle"]
              - {
                  label: "Blurb",
                  name: "blurb",
                  widget: text,
                  required: false,
                  description: "Blurb to describe product, used on feature pages. If no blurb provided, one is generated from the product description",
                }

      - label: "Local Talent"
        name: "localProducts"
        file: "src/data/local.json"
        fields:
          - {
              label: Title,
              name: title,
              widget: hidden,
              default: "local-products",
            }
          - label: "Local Talent Listing"
            name: "localList"
            description: "Arrange this list to control position of featured items."
            widget: "list"
            fields:
              - label: "Product"
                name: "product"
                widget: "relation"
                collection: "products"
                searchFields: ["productType", "title", "subtitle"]
                valueField: "name"
                displayFields: ["productType", "title", "subtitle"]
              - {
                  label: "Blurb",
                  name: "blurb",
                  widget: text,
                  required: false,
                  description: "Blurb to describe product, used on feature pages. If no blurb provided, one is generated from the product description",
                }
      - label: "Indie Corner"
        name: "indieProducts"
        file: "src/data/indie.json"
        fields:
          - {
              label: Title,
              name: title,
              widget: hidden,
              default: "indie-products",
            }
          - label: "Indie Corner Listing"
            name: "indieList"
            description: "Arrange this list to control position of featured items."
            widget: "list"
            fields:
              - label: "Product"
                name: "product"
                widget: "relation"
                collection: "products"
                searchFields: ["productType", "title", "subtitle"]
                valueField: "name"
                displayFields: ["productType", "title", "subtitle"]
              - {
                  label: "Blurb",
                  name: "blurb",
                  widget: text,
                  required: false,
                  description: "Blurb to describe product, used on feature pages. If no blurb provided, one is generated from the product description",
                }
